ALTER SESSION set NLS_DATE_FORMAT = 'DD/MM/YYYY';
DROP TABLE DETALLE_EVALUACION;
DROP TABLE EVALUACION;
DROP TABLE TRATAMIENTO;
DROP TABLE DIAGNOSTICO;
DROP TABLE SINTOMA;
DROP TABLE PACIENTE;
DROP TABLE EMPLEADO;
DROP TABLE TITULO;
DROP TABLE TEMPORAL;

CREATE TABLE TEMPORAL (
    nombre_empleado VARCHAR2(1000),
    apellido_empleado VARCHAR2(1000),
    direccion_empleado VARCHAR2(1000),
    telefono_empleado VARCHAR2(1000),
    genero_empleado VARCHAR2(1000),
    fecha_nacimiento_empleado VARCHAR2(1000),
    titulo_del_empleado VARCHAR2(1000),
    nombre_paciente VARCHAR2(1000),
    apellido_paciente VARCHAR2(1000),
    direccion_paciente VARCHAR2(1000),
    telefono_paciente VARCHAR2(1000),
    genero_paciente VARCHAR2(1000),
    fecha_nacimiento_paciente VARCHAR2(1000),
    altura VARCHAR2(1000),
    peso VARCHAR2(1000),
    fecha_evaluacion VARCHAR2(1000),
    sintoma_del_paciente VARCHAR2(1000),
    diagnostico_del_sintoma VARCHAR2(1000),
    rango_del_diagnostico VARCHAR2(1000),
    fecha_tratamiento VARCHAR2(1000),
    tratamiento_aplicado VARCHAR2(1000)
);

CREATE TABLE TITULO (
    id_titulo INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY(id_titulo)
);

CREATE TABLE EMPLEADO (
    id_empleado INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    direccion VARCHAR(200) NOT NULL,
    telefono INTEGER NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    genero VARCHAR(1) NOT NULL,
    id_titulo INTEGER NOT NULL,
    PRIMARY KEY (id_empleado), 
    FOREIGN KEY (id_titulo)	REFERENCES TITULO (id_titulo)
);

CREATE TABLE PACIENTE (
    id_paciente INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    direccion VARCHAR(200) NOT NULL,
    telefono INTEGER NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    genero VARCHAR(1) NOT NULL,
    altura_mt NUMBER NOT NULL,
    peso NUMBER NOT NULL,
    PRIMARY KEY (id_paciente)
);

CREATE TABLE SINTOMA (
    id_sintoma INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY (id_sintoma)
);

CREATE TABLE DIAGNOSTICO (
    id_diagnostico INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY (id_diagnostico)
);

CREATE TABLE TRATAMIENTO (
    id_tratamiento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR (50) NOT NULL,
    PRIMARY KEY (id_tratamiento)
);

CREATE TABLE EVALUACION (
    id_evaluacion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    fecha_evaluacion DATE,
    id_sintoma INTEGER,
    id_empleado INTEGER,
    id_paciente INTEGER NOT NULL,
    PRIMARY KEY (id_evaluacion),
    FOREIGN KEY (id_sintoma) REFERENCES SINTOMA (id_sintoma),
    FOREIGN KEY (id_empleado) REFERENCES EMPLEADO (id_empleado),
    FOREIGN KEY (id_paciente) REFERENCES PACIENTE (id_paciente)
);

CREATE TABLE DETALLE_EVALUACION (
    id_detalle_evaluacion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_evaluacion INTEGER,
    id_diagnostico INTEGER,
    id_tratamiento INTEGER,
    rango_diagnostico SMALLINT,
    fecha_tratamiento DATE,
    PRIMARY KEY (id_detalle_evaluacion),
    FOREIGN KEY (id_evaluacion) REFERENCES EVALUACION (id_evaluacion),
    FOREIGN KEY (id_diagnostico) REFERENCES DIAGNOSTICO (id_diagnostico),
    FOREIGN KEY (id_tratamiento) REFERENCES TRATAMIENTO (id_tratamiento)
);

/*
Debido a que se esta ejecutando oracle atraves de docker, hay que seguir los siguientes pasos:
1. Copiar el archivo a docker
sudo docker cp /home/douglas/Descargas/BIG_SMOKE_DATA.csv c5953334a404:/home/oracle
2. Copiar el archivo de control
sudo docker cp '/home/douglas/Documentos/Sistemas de Base de Datos 1/Laboratorio/Proyecto 1/[BD1]ArchivoControl.ctl' c5953334a404:/home/oracle
3. Ingresar a la consola del container
sudo docker exec -it --user=oracle oracle_bd bash
3. Ejecutar el comando para el archivo de control
sqlldr userid=SYSTEM/psw123@ORCLCDB control='[BD1]ArchivoControl.ctl' log=track.log
*/